//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tonrich.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tonrich.Shared.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyHaveAccountMessage {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}.
        /// </summary>
        public static string AreYouSureWannaDelete {
            get {
                return ResourceManager.GetString("AreYouSureWannaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your Spam/Junk, if you could not find it in the Inbox..
        /// </summary>
        public static string CheckSpamMailMessage {
            get {
                return ResourceManager.GetString("CheckSpamMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string CompareAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CompareAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a confirmation link to your email address.
        ///Please confirm your email by clicking on the link..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email Address.
        /// </summary>
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be processed because of conflict in the request.
        /// </summary>
        public static string ConflicException {
            get {
                return ResourceManager.GetString("ConflicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color.
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string DeleteAccountPrompt {
            get {
                return ResourceManager.GetString("DeleteAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account?.
        /// </summary>
        public static string DontHaveAccountMessage {
            get {
                return ResourceManager.GetString("DontHaveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailAddressAttribute_ValidationError {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is already confirmed..
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation Failed!.
        /// </summary>
        public static string EmailConfirmationFailedMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed Successfully!.
        /// </summary>
        public static string EmailConfirmedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading file.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the requested resource is forbidden.
        /// </summary>
        public static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address you have been signed up with so we can send a reset password link to your email address..
        /// </summary>
        public static string ForgetPasswordMessage {
            get {
                return ResourceManager.GetString("ForgetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GenderOther {
            get {
                return ResourceManager.GetString("GenderOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repo.
        /// </summary>
        public static string GitHubRepo {
            get {
                return ResourceManager.GetString("GitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to today.
        /// </summary>
        public static string GoToToday {
            get {
                return ResourceManager.GetString("GoToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your multi-mode (WASM, Server, Hybrid, pre-rendering) Blazor app easily in the shortest time ever!.
        /// </summary>
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonrich Home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the confirmation link either is invalid or has expired..
        /// </summary>
        public static string InvalidConfirmationLinkMessage {
            get {
                return ResourceManager.GetString("InvalidConfirmationLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try our plug-in now.
        /// </summary>
        public static string LandingBrowserBtn {
            get {
                return ResourceManager.GetString("LandingBrowserBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTRODUCING.
        /// </summary>
        public static string LandingBrowserGrayBox {
            get {
                return ResourceManager.GetString("LandingBrowserGrayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonrich browser plug-in works seamlessly with popular sites such as fragment.com, tonscan.org and tonapi.io. The only thing you need to do is hover over a wallet address on these sites, Tonrich will show users a comprehensive overview of the wallet&apos;s activity, balance, transactions, and more..
        /// </summary>
        public static string LandingBrowserText {
            get {
                return ResourceManager.GetString("LandingBrowserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser plug-in.
        /// </summary>
        public static string LandingBrowserTitle {
            get {
                return ResourceManager.GetString("LandingBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTRODUCING.
        /// </summary>
        public static string LandingCheckGrayBox {
            get {
                return ResourceManager.GetString("LandingCheckGrayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the wallet address here.
        /// </summary>
        public static string LandingCheckInputPlaceholder {
            get {
                return ResourceManager.GetString("LandingCheckInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use our Website just by a click to get ta comprehensive overview of the wallet&apos;s activity, balance, transactions, and more, just enter the wallet address, an image like this will enrich you:.
        /// </summary>
        public static string LandingCheckText {
            get {
                return ResourceManager.GetString("LandingCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check it now.
        /// </summary>
        public static string LandingCheckTitle {
            get {
                return ResourceManager.GetString("LandingCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOVER TONRICH.
        /// </summary>
        public static string LandingDiscoverGrayBox {
            get {
                return ResourceManager.GetString("LandingDiscoverGrayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is.
        /// </summary>
        public static string LandingDiscoverTitle1 {
            get {
                return ResourceManager.GetString("LandingDiscoverTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TonRich?.
        /// </summary>
        public static string LandingDiscoverTitle2 {
            get {
                return ResourceManager.GetString("LandingDiscoverTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonrich is the ultimate tool for anyone who wants to uncover the secrets of TON wallets and gain valuable insights into the NFT market. Download Tonrich today and start your journey into the world of TON wallets and NFT auctions!.
        /// </summary>
        public static string LandingDiscoverTxt1 {
            get {
                return ResourceManager.GetString("LandingDiscoverTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use Tonrich to compare different wallets and see how they relate to each other..
        /// </summary>
        public static string LandingDiscoverTxt2 {
            get {
                return ResourceManager.GetString("LandingDiscoverTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try our plug-in now.
        /// </summary>
        public static string LandingHeroBtn {
            get {
                return ResourceManager.GetString("LandingHeroBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TonRich.
        /// </summary>
        public static string LandingHeroTitle {
            get {
                return ResourceManager.GetString("LandingHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handy tool for deep insight into TON wallets and NFT auctions.
        /// </summary>
        public static string LandingHeroTxt {
            get {
                return ResourceManager.GetString("LandingHeroTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use it?.
        /// </summary>
        public static string LandingHowTitle {
            get {
                return ResourceManager.GetString("LandingHowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try our bot now.
        /// </summary>
        public static string LandingTelegramBtn {
            get {
                return ResourceManager.GetString("LandingTelegramBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use the Tonrich Telegram bot easily to get ta comprehensive overview of the wallet&apos;s activity, balance, transactions, and more, just by sending the wallet address to the bot. The bot will answer you by sending an image like this:.
        /// </summary>
        public static string LandingTelegramText {
            get {
                return ResourceManager.GetString("LandingTelegramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram bot.
        /// </summary>
        public static string LandingTelegramTitle {
            get {
                return ResourceManager.GetString("LandingTelegramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work seamlessly with popular services.
        /// </summary>
        public static string LandingWorkSeamlessly {
            get {
                return ResourceManager.GetString("LandingWorkSeamlessly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length..
        /// </summary>
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;..
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven’t you received the confirmation email?.
        /// </summary>
        public static string NotReceivedConfirmationEmailMessage {
            get {
                return ResourceManager.GetString("NotReceivedConfirmationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password changed successfully..
        /// </summary>
        public static string PasswordChangedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        public static string ProfileUpdatedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try TonRich.
        /// </summary>
        public static string RecapBtn {
            get {
                return ResourceManager.GetString("RecapBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to know more about TON wallets and their transactions?.
        /// </summary>
        public static string RecapText1 {
            get {
                return ResourceManager.GetString("RecapText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to access rich and detailed information about any wallet in TON with just a simple hover?.
        /// </summary>
        public static string RecapText2 {
            get {
                return ResourceManager.GetString("RecapText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to gain a competitive edge in the NFT market by analyzing the behavior of your competitors in real-time?.
        /// </summary>
        public static string RecapText3 {
            get {
                return ResourceManager.GetString("RecapText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s recap!.
        /// </summary>
        public static string RecapTitle {
            get {
                return ResourceManager.GetString("RecapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation link has been re-sent to your email address..
        /// </summary>
        public static string ResendConfirmationLinkMessage {
            get {
                return ResourceManager.GetString("ResendConfirmationLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email.
        /// </summary>
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset password link has been sent to your email address..
        /// </summary>
        public static string ResetPasswordLinkSentMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid.
        /// </summary>
        public static string ResourceValidationException {
            get {
                return ResourceManager.GetString("ResourceValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating with server.
        /// </summary>
        public static string RestException {
            get {
                return ResourceManager.GetString("RestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your birth date.
        /// </summary>
        public static string SelectBirthDate {
            get {
                return ResourceManager.GetString("SelectBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server..
        /// </summary>
        public static string ServerConnectionException {
            get {
                return ResourceManager.GetString("ServerConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in as different user.
        /// </summary>
        public static string SignInAsDifferentUser {
            get {
                return ResourceManager.GetString("SignInAsDifferentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Sign out?.
        /// </summary>
        public static string SignOutPrompt {
            get {
                return ResourceManager.GetString("SignOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SingUpTitle {
            get {
                return ResourceManager.GetString("SingUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is accept terms?.
        /// </summary>
        public static string TermsAccepted {
            get {
                return ResourceManager.GetString("TermsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        public static string TermsMessage {
            get {
                return ResourceManager.GetString("TermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        public static string TooManyRequestsExceptions {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request lacks valid authentication credentials.
        /// </summary>
        public static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error has occurred.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was modified by another user after you got the original data. the operation was canceled..
        /// </summary>
        public static string UpdateConcurrencyException {
            get {
                return ResourceManager.GetString("UpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a new profile image.
        /// </summary>
        public static string UploadNewProfileImage {
            get {
                return ResourceManager.GetString("UploadNewProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User image could not be found.
        /// </summary>
        public static string UserImageCouldNotBeFound {
            get {
                return ResourceManager.GetString("UserImageCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out. Try again in {0}.
        /// </summary>
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not exist..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested the confirmation email. Try again in {0}.
        /// </summary>
        public static string WaitForConfirmationEmailResendDelay {
            get {
                return ResourceManager.GetString("WaitForConfirmationEmailResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested the reset password email. Try again in {0}.
        /// </summary>
        public static string WaitForResetPasswordEmailResendDelay {
            get {
                return ResourceManager.GetString("WaitForResetPasswordEmailResendDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re sign in as.
        /// </summary>
        public static string YouAreSignInAs {
            get {
                return ResourceManager.GetString("YouAreSignInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to our terms..
        /// </summary>
        public static string YouHaveToAcceptTerms {
            get {
                return ResourceManager.GetString("YouHaveToAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be signed in to continue..
        /// </summary>
        public static string YouNeedToSignIn {
            get {
                return ResourceManager.GetString("YouNeedToSignIn", resourceCulture);
            }
        }
    }
}
