// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blink': string;
  'blinker': string;
  'tonrich-page': string;
  'tonrich-page-Display': string;
  'tonrich-page-Display-visible': string;
}
export const cssExports: CssExports;
export default cssExports;
